-- gen-register.lua
-- 用法: lua gen-register.lua <proto文件> <输出目录> <包名>
-- 示例: lua gen-register.lua protobuf/game.proto pb/game game

local proto_file = arg[1]
local out_dir    = arg[2]
local pkg        = arg[3]

if not proto_file or not out_dir or not pkg then
    io.stderr:write("usage: lua gen-register.lua <proto> <out_dir> <pkg>\n")
    os.exit(1)
end

-- 读取 proto 文件
local f = io.open(proto_file, "r")
if not f then
    io.stderr:write("cannot open: " .. proto_file .. "\n")
    os.exit(1)
end
local content = f:read("*a")
f:close()

-- 提取所有 message 名
local messages = {}
for name in content:gmatch("^message%s+(%w+)%s*{") do
    table.insert(messages, name)
end
-- 兼容非行首的 message（多行文件 gmatch 默认不跨行）
for name in content:gmatch("\nmessage%s+(%w+)%s*{") do
    table.insert(messages, name)
end

if #messages == 0 then
    io.stderr:write("no messages found in " .. proto_file .. "\n")
    os.exit(1)
end

-- 生成 register.go
local out_path = out_dir .. "/register.go"
local out = io.open(out_path, "w")
if not out then
    io.stderr:write("cannot write: " .. out_path .. "\n")
    os.exit(1)
end

out:write("// Code generated by gen-register.lua. DO NOT EDIT.\n")
out:write("package " .. pkg .. "\n\n")
out:write('import "goAcotr/gameServer/codec"\n\n')
out:write("func init() {\n")
out:write("\tcodec.RegisterMsg(\n")
for _, name in ipairs(messages) do
    out:write("\t\t&" .. name .. "{},\n")
end
out:write("\t)\n}\n")
out:close()

print(string.format("generated %s (%d messages)", out_path, #messages))
